//! SystemVerilog pretty-printer. Assumes IR invariants hold; does not
//! validate.
//!
//! Synchronous-design discipline: a single CLK (posedge) and a single
//! RST_N (async, active-low) drive every flop in the module.

use crate::ir::{GateOp, Module, Node, NodeId};
use std::fmt::Write;

pub fn to_sv(m: &Module) -> String {
    let mut out = String::new();
    writeln!(out, "// Generated by anvil. Module: {}", m.name).unwrap();
    writeln!(out, "module {} (", m.name).unwrap();

    let has_flops = !m.flops.is_empty();
    let mut first = true;

    // Port list. clk/rst_n appear only when at least one flop exists.
    for p in &m.inputs {
        let is_clock = m.clock == Some(p.id);
        let is_reset = m.reset == Some(p.id);
        if (is_clock || is_reset) && !has_flops {
            continue;
        }
        if !first {
            writeln!(out, ",").unwrap();
        }
        first = false;
        write!(out, "    input  logic {} {}", width_decl(p.width), p.name).unwrap();
    }
    for p in &m.outputs {
        if !first {
            writeln!(out, ",").unwrap();
        }
        first = false;
        write!(out, "    output logic {} {}", width_decl(p.width), p.name).unwrap();
    }
    writeln!(out).unwrap();
    writeln!(out, ");").unwrap();
    writeln!(out).unwrap();

    // Flop register declarations.
    for flop in &m.flops {
        writeln!(out, "    logic {} r_{};", width_decl(flop.width), flop.id).unwrap();
    }
    if has_flops {
        writeln!(out).unwrap();
    }

    // Internal wire declarations for every Gate node.
    for (idx, node) in m.nodes.iter().enumerate() {
        if let Node::Gate { width, .. } = node {
            writeln!(out, "    wire {} w_{};", width_decl(*width), idx).unwrap();
        }
    }
    writeln!(out).unwrap();

    // Combinational assigns.
    for (idx, node) in m.nodes.iter().enumerate() {
        if let Node::Gate { op, operands, .. } = node {
            let rhs = render_gate(*op, operands, m);
            writeln!(out, "    assign w_{} = {};", idx, rhs).unwrap();
        }
    }
    if !m.nodes.is_empty() {
        writeln!(out).unwrap();
    }

    // Sequential always_ff blocks. Single CLK (posedge), single RST_N (async).
    if has_flops {
        let clk = port_name(m, m.clock.expect("flops require a clock"));
        let rst = port_name(m, m.reset.expect("flops require a reset"));
        writeln!(
            out,
            "    always_ff @(posedge {} or negedge {}) begin",
            clk, rst
        )
        .unwrap();
        writeln!(out, "        if (!{}) begin", rst).unwrap();
        for flop in &m.flops {
            writeln!(
                out,
                "            r_{} <= {}'h{:x};",
                flop.id, flop.width, flop.reset_val
            )
            .unwrap();
        }
        writeln!(out, "        end else begin").unwrap();
        for flop in &m.flops {
            let d_id = flop.d.expect("flop D must be set before emission");
            let d_ref = node_ref(d_id, m);
            writeln!(out, "            r_{} <= {};", flop.id, d_ref).unwrap();
        }
        writeln!(out, "        end").unwrap();
        writeln!(out, "    end").unwrap();
        writeln!(out).unwrap();
    }

    // Output port assigns.
    for (port_id, node_id) in &m.drives {
        let out_port = m.outputs.iter().find(|p| p.id == *port_id).unwrap();
        let rhs = node_ref(*node_id, m);
        writeln!(out, "    assign {} = {};", out_port.name, rhs).unwrap();
    }

    writeln!(out, "endmodule").unwrap();
    out
}

fn width_decl(w: u32) -> String {
    if w == 1 {
        String::new()
    } else {
        format!("[{}:0]", w - 1)
    }
}

fn port_name(m: &Module, id: crate::ir::PortId) -> String {
    m.inputs
        .iter()
        .chain(m.outputs.iter())
        .find(|p| p.id == id)
        .map(|p| p.name.clone())
        .unwrap_or_else(|| format!("port_{}", id))
}

fn node_ref(id: NodeId, m: &Module) -> String {
    match &m.nodes[id as usize] {
        Node::PrimaryInput { port, .. } => m
            .inputs
            .iter()
            .find(|p| p.id == *port)
            .unwrap()
            .name
            .clone(),
        Node::Constant { width, value } => format!("{}'h{:x}", width, value),
        Node::FlopQ { flop, .. } => format!("r_{}", flop),
        Node::Gate { .. } => format!("w_{}", id),
    }
}

fn render_gate(op: GateOp, operands: &[NodeId], m: &Module) -> String {
    use GateOp::*;
    let a = |i: usize| node_ref(operands[i], m);
    match op {
        And => format!("{} & {}", a(0), a(1)),
        Or => format!("{} | {}", a(0), a(1)),
        Xor => format!("{} ^ {}", a(0), a(1)),
        Not => format!("~{}", a(0)),
        Add => format!("{} + {}", a(0), a(1)),
        Sub => format!("{} - {}", a(0), a(1)),
        Mul => format!("{} * {}", a(0), a(1)),
        Eq => format!("{} == {}", a(0), a(1)),
        Neq => format!("{} != {}", a(0), a(1)),
        Lt => format!("{} < {}", a(0), a(1)),
        Gt => format!("{} > {}", a(0), a(1)),
        Le => format!("{} <= {}", a(0), a(1)),
        Ge => format!("{} >= {}", a(0), a(1)),
        Mux => format!("({}) ? ({}) : ({})", a(0), a(1), a(2)),
        Slice { hi, lo } => format!("{}[{}:{}]", a(0), hi, lo),
        Concat => {
            let parts: Vec<_> = operands.iter().map(|id| node_ref(*id, m)).collect();
            format!("{{{}}}", parts.join(", "))
        }
        RedAnd => format!("&({})", a(0)),
        RedOr => format!("|({})", a(0)),
        RedXor => format!("^({})", a(0)),
        Shl => format!("{} << {}", a(0), a(1)),
        Shr => format!("{} >> {}", a(0), a(1)),
    }
}
