//! SystemVerilog pretty-printer. Assumes IR invariants hold; does not
//! validate.
//!
//! Synchronous-design discipline: a single CLK (posedge) and a single
//! RST_N (async, active-low) drive every flop in the module.

use crate::ir::{GateOp, Module, Node, NodeId};
use std::fmt::Write;
use tracing::{debug, info, instrument};

#[instrument(level = "info", skip(m), fields(module = %m.name))]
pub fn to_sv(m: &Module) -> String {
    // Emitter is a dumb serialiser. It assumes all IR invariants —
    // including Rule 18 (no orphan gates) — were enforced upstream
    // during construction. The emitter walks `m.nodes` in order and
    // writes a wire declaration + assign for each Gate, plus a flop
    // declaration + always_ff branch for each Flop, plus output
    // drives. No filtering, no reachability checks.
    let names = build_names(m);
    info!(
        gates = m
            .nodes
            .iter()
            .filter(|n| matches!(n, Node::Gate { .. }))
            .count(),
        flops = m.flops.len(),
        inputs = m.inputs.len(),
        outputs = m.outputs.len(),
        "✍️ emit SV"
    );
    let mut out = String::new();
    writeln!(out, "// Generated by anvil. Module: {}", m.name).unwrap();
    writeln!(out, "module {} (", m.name).unwrap();

    let has_flops = !m.flops.is_empty();
    let mut first = true;

    // Port list. clk/rst_n appear only when at least one flop exists.
    for p in &m.inputs {
        let is_clock = m.clock == Some(p.id);
        let is_reset = m.reset == Some(p.id);
        if (is_clock || is_reset) && !has_flops {
            continue;
        }
        if !first {
            writeln!(out, ",").unwrap();
        }
        first = false;
        write!(out, "    input  logic {} {}", width_decl(p.width), p.name).unwrap();
    }
    for p in &m.outputs {
        if !first {
            writeln!(out, ",").unwrap();
        }
        first = false;
        write!(out, "    output logic {} {}", width_decl(p.width), p.name).unwrap();
    }
    writeln!(out).unwrap();
    writeln!(out, ");").unwrap();
    writeln!(out).unwrap();

    // Flop register declarations.
    for flop in &m.flops {
        writeln!(
            out,
            "    logic {} {};",
            width_decl(flop.width),
            flop_name(flop.id)
        )
        .unwrap();
    }
    if has_flops {
        writeln!(out).unwrap();
    }

    // Internal wire declarations for every Gate node.
    for (idx, node) in m.nodes.iter().enumerate() {
        if let Node::Gate { width, .. } = node {
            writeln!(
                out,
                "    wire {} {};",
                width_decl(*width),
                names[idx].as_ref().expect("gate name assigned")
            )
            .unwrap();
        }
    }
    writeln!(out).unwrap();

    // Combinational assigns for every gate.
    for (idx, node) in m.nodes.iter().enumerate() {
        if let Node::Gate { op, operands, .. } = node {
            let rhs = render_gate(*op, operands, m, &names);
            writeln!(
                out,
                "    assign {} = {};",
                names[idx].as_ref().unwrap(),
                rhs
            )
            .unwrap();
        }
    }
    if !m.nodes.is_empty() {
        writeln!(out).unwrap();
    }

    // Sequential always_ff blocks. Single CLK (posedge), single RST_N (async).
    if has_flops {
        let clk = port_name(m, m.clock.expect("flops require a clock"));
        let rst = port_name(m, m.reset.expect("flops require a reset"));
        writeln!(
            out,
            "    always_ff @(posedge {} or negedge {}) begin",
            clk, rst
        )
        .unwrap();
        writeln!(out, "        if (!{}) begin", rst).unwrap();
        for flop in &m.flops {
            writeln!(
                out,
                "            {} <= {}'h{:x};",
                flop_name(flop.id),
                flop.width,
                flop.reset_val
            )
            .unwrap();
        }
        writeln!(out, "        end else begin").unwrap();
        for flop in &m.flops {
            let d_id = flop.d.expect("flop D must be set before emission");
            let d_ref = node_ref(d_id, m, &names);
            writeln!(out, "            {} <= {};", flop_name(flop.id), d_ref).unwrap();
        }
        writeln!(out, "        end").unwrap();
        writeln!(out, "    end").unwrap();
        writeln!(out).unwrap();
    }

    // Output port assigns.
    for (port_id, node_id) in &m.drives {
        let out_port = m.outputs.iter().find(|p| p.id == *port_id).unwrap();
        let rhs = node_ref(*node_id, m, &names);
        writeln!(out, "    assign {} = {};", out_port.name, rhs).unwrap();
    }

    writeln!(out, "endmodule").unwrap();
    out
}

/// Deterministic identifier for a `GateOp` — the per-kind prefix used
/// in emitted wire names (`<kind>_<counter>`). Kinds are lowercase
/// snake_case. Suffixed with a trailing `_` in callers.
fn gate_kind_name(op: GateOp) -> &'static str {
    use GateOp::*;
    match op {
        And => "and",
        Or => "or",
        Xor => "xor",
        Not => "not",
        Add => "add",
        Sub => "sub",
        Mul => "mul",
        Eq => "eq",
        Neq => "neq",
        Lt => "lt",
        Gt => "gt",
        Le => "le",
        Ge => "ge",
        Mux => "mux",
        Slice { .. } => "slice",
        Concat => "concat",
        RedAnd => "red_and",
        RedOr => "red_or",
        RedXor => "red_xor",
        Shl => "shl",
        Shr => "shr",
    }
}

fn flop_name(id: u32) -> String {
    format!("flop_{}", id)
}

/// Walk the module once, assigning per-kind counters to every gate.
/// Non-gate nodes (`PrimaryInput`, `Constant`, `FlopQ`) get `None`
/// because their reference form is derived from elsewhere (port name,
/// literal, flop id).
fn build_names(m: &Module) -> Vec<Option<String>> {
    use std::collections::BTreeMap;
    // BTreeMap for deterministic iteration order when we log the
    // per-kind counts below. HashMap would work for correctness but
    // would surface non-determinism in trace output.
    let mut counters: BTreeMap<&'static str, u32> = BTreeMap::new();
    let mut names: Vec<Option<String>> = Vec::with_capacity(m.nodes.len());
    for node in &m.nodes {
        let name = match node {
            Node::Gate { op, .. } => {
                let kind = gate_kind_name(*op);
                let counter = counters.entry(kind).or_insert(0);
                let n = *counter;
                *counter += 1;
                Some(format!("{}_{}", kind, n))
            }
            _ => None,
        };
        names.push(name);
    }
    debug!(
        per_kind = ?counters,
        "build_names: per-kind counters assigned"
    );
    names
}

fn width_decl(w: u32) -> String {
    if w == 1 {
        String::new()
    } else {
        format!("[{}:0]", w - 1)
    }
}

fn port_name(m: &Module, id: crate::ir::PortId) -> String {
    m.inputs
        .iter()
        .chain(m.outputs.iter())
        .find(|p| p.id == id)
        .map(|p| p.name.clone())
        .unwrap_or_else(|| format!("port_{}", id))
}

fn node_ref(id: NodeId, m: &Module, names: &[Option<String>]) -> String {
    match &m.nodes[id as usize] {
        Node::PrimaryInput { port, .. } => m
            .inputs
            .iter()
            .find(|p| p.id == *port)
            .unwrap()
            .name
            .clone(),
        Node::Constant { width, value } => format!("{}'h{:x}", width, value),
        Node::FlopQ { flop, .. } => flop_name(*flop),
        Node::Gate { .. } => names[id as usize]
            .clone()
            .expect("gate name assigned by build_names"),
    }
}

fn render_gate(op: GateOp, operands: &[NodeId], m: &Module, names: &[Option<String>]) -> String {
    use GateOp::*;
    let a = |i: usize| node_ref(operands[i], m, names);
    let joined = |sep: &str| -> String {
        operands
            .iter()
            .map(|id| node_ref(*id, m, names))
            .collect::<Vec<_>>()
            .join(sep)
    };
    match op {
        // N-arity associative ops: join operand refs with the infix symbol.
        // For N = 2 this recovers the classic binary form.
        And => joined(" & "),
        Or => joined(" | "),
        Xor => joined(" ^ "),
        Add => joined(" + "),
        Mul => joined(" * "),
        // Sub is strictly 2-arity (not associative).
        Sub => format!("{} - {}", a(0), a(1)),
        Not => format!("~{}", a(0)),
        Eq => format!("{} == {}", a(0), a(1)),
        Neq => format!("{} != {}", a(0), a(1)),
        Lt => format!("{} < {}", a(0), a(1)),
        Gt => format!("{} > {}", a(0), a(1)),
        Le => format!("{} <= {}", a(0), a(1)),
        Ge => format!("{} >= {}", a(0), a(1)),
        Mux => format!("({}) ? ({}) : ({})", a(0), a(1), a(2)),
        Slice { hi, lo } => format!("{}[{}:{}]", a(0), hi, lo),
        Concat => {
            // If every operand points at the same NodeId, emit the
            // canonical SystemVerilog replication form `{N{expr}}`
            // instead of a flat list `{expr, expr, ..., expr}`. This
            // is the idiom for broadcasting a 1-bit select across a
            // W-bit mask (`{W{sel_i}} & data_i` in one-hot muxes).
            // Synthesis-equivalent; purely a readability fix.
            if operands.len() >= 2 && operands.iter().all(|id| *id == operands[0]) {
                return format!("{{{}{{{}}}}}", operands.len(), a(0));
            }
            let parts: Vec<_> = operands.iter().map(|id| node_ref(*id, m, names)).collect();
            format!("{{{}}}", parts.join(", "))
        }
        RedAnd => format!("&({})", a(0)),
        RedOr => format!("|({})", a(0)),
        RedXor => format!("^({})", a(0)),
        Shl => format!("{} << {}", a(0), a(1)),
        Shr => format!("{} >> {}", a(0), a(1)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{
        DepSet, Direction, Flop, FlopKind, FlopMux, GateOp, Module, Node, Port, ResetKind,
    };

    fn port(id: u32, name: &str, width: u32, dir: Direction) -> Port {
        Port {
            id,
            name: name.into(),
            width,
            dir,
        }
    }

    #[test]
    fn emits_module_header_and_endmodule() {
        let mut m = Module {
            name: "m_test".into(),
            ..Module::default()
        };
        let a = port(0, "a", 4, Direction::In);
        let o = port(1, "o", 4, Direction::Out);
        m.inputs.push(a.clone());
        m.outputs.push(o.clone());
        m.nodes.push(Node::PrimaryInput { port: 0, width: 4 });
        m.drives.push((1, 0));
        let sv = to_sv(&m);
        assert!(sv.contains("module m_test ("));
        assert!(sv.contains("endmodule"));
        assert!(sv.contains("input  logic [3:0] a"));
        assert!(sv.contains("output logic [3:0] o"));
        assert!(sv.contains("assign o = a;"));
    }

    #[test]
    fn omits_clk_rst_n_when_no_flops() {
        // clk/rst_n are declared as input ports in the IR, but the emitter
        // must hide them when the module has zero flops.
        let mut m = Module {
            name: "m".into(),
            ..Module::default()
        };
        m.inputs.push(port(0, "clk", 1, Direction::In));
        m.inputs.push(port(1, "rst_n", 1, Direction::In));
        m.inputs.push(port(2, "a", 4, Direction::In));
        m.outputs.push(port(3, "o", 4, Direction::Out));
        m.clock = Some(0);
        m.reset = Some(1);
        m.nodes.push(Node::PrimaryInput { port: 2, width: 4 });
        m.drives.push((3, 0));
        let sv = to_sv(&m);
        assert!(
            !sv.contains("clk"),
            "clk must be omitted when module has no flops:\n{sv}"
        );
        assert!(
            !sv.contains("rst_n"),
            "rst_n must be omitted when module has no flops"
        );
        assert!(sv.contains("input  logic [3:0] a"));
    }

    #[test]
    fn emits_always_ff_with_single_clk_and_async_rst_n() {
        let mut m = Module {
            name: "m".into(),
            ..Module::default()
        };
        m.inputs.push(port(0, "clk", 1, Direction::In));
        m.inputs.push(port(1, "rst_n", 1, Direction::In));
        m.inputs.push(port(2, "a", 4, Direction::In));
        m.outputs.push(port(3, "o", 4, Direction::Out));
        m.clock = Some(0);
        m.reset = Some(1);
        // PrimaryInput node for `a`, FlopQ node for the flop.
        m.nodes.push(Node::PrimaryInput { port: 2, width: 4 }); // node 0
        m.nodes.push(Node::FlopQ { flop: 0, width: 4 }); // node 1
        m.flops.push(Flop {
            id: 0,
            width: 4,
            d: Some(0), // D := a (the PrimaryInput)
            q: 1,
            reset_val: 0,
            reset_kind: ResetKind::Async,
            kind: FlopKind::ZeroDefault,
            mux: FlopMux::None,
        });
        m.drives.push((3, 1)); // o := Q
        let sv = to_sv(&m);
        assert!(sv.contains("input  logic  clk"), "clk input missing:\n{sv}");
        assert!(sv.contains("input  logic  rst_n"), "rst_n input missing");
        assert!(
            sv.contains("always_ff @(posedge clk or negedge rst_n)"),
            "canonical always_ff header missing"
        );
        assert!(sv.contains("if (!rst_n)"), "active-low reset guard missing");
        assert!(sv.contains("flop_0 <= 4'h0;"), "reset branch missing");
        assert!(
            sv.contains("flop_0 <= a;"),
            "active-clock assignment missing"
        );
        assert!(
            sv.contains("assign o = flop_0;"),
            "output wiring to Q missing"
        );
    }

    #[test]
    fn constant_and_operators_rendered() {
        let mut m = Module {
            name: "m".into(),
            ..Module::default()
        };
        m.inputs.push(port(0, "a", 8, Direction::In));
        m.inputs.push(port(1, "b", 8, Direction::In));
        m.outputs.push(port(2, "o", 8, Direction::Out));
        m.nodes.push(Node::PrimaryInput { port: 0, width: 8 }); // 0
        m.nodes.push(Node::PrimaryInput { port: 1, width: 8 }); // 1
        m.nodes.push(Node::Constant {
            width: 8,
            value: 0x5a,
        }); // 2
            // w_3 = a & b
        m.nodes.push(Node::Gate {
            op: GateOp::And,
            operands: vec![0, 1],
            width: 8,
            deps: DepSet::union(&[&DepSet::from_port(0), &DepSet::from_port(1)]),
        }); // 3
            // w_4 = w_3 ^ 8'h5a
        m.nodes.push(Node::Gate {
            op: GateOp::Xor,
            operands: vec![3, 2],
            width: 8,
            deps: DepSet::union(&[&DepSet::from_port(0), &DepSet::from_port(1)]),
        }); // 4
        m.drives.push((2, 4));
        let sv = to_sv(&m);
        assert!(sv.contains("assign and_0 = a & b;"));
        assert!(sv.contains("assign xor_0 = and_0 ^ 8'h5a;"));
        assert!(sv.contains("assign o = xor_0;"));
    }

    #[test]
    fn slice_and_concat_rendered() {
        // Both gates must be reachable from the output drive so the
        // Rule-18 live-set filter keeps them. Chain: o <- concat <-
        // (slice, slice); slice <- a.
        let mut m = Module {
            name: "m".into(),
            ..Module::default()
        };
        m.inputs.push(port(0, "a", 8, Direction::In));
        m.outputs.push(port(1, "o", 8, Direction::Out));
        m.nodes.push(Node::PrimaryInput { port: 0, width: 8 }); // 0
        m.nodes.push(Node::Gate {
            op: GateOp::Slice { hi: 3, lo: 0 },
            operands: vec![0],
            width: 4,
            deps: DepSet::from_port(0),
        }); // 1
        m.nodes.push(Node::Gate {
            op: GateOp::Concat,
            operands: vec![1, 1],
            width: 8,
            deps: DepSet::from_port(0),
        }); // 2
        m.drives.push((1, 2));
        let sv = to_sv(&m);
        assert!(sv.contains("assign slice_0 = a[3:0];"));
        assert!(sv.contains("assign concat_0 = {2{slice_0}};"));
    }

    #[test]
    fn mux_rendered_with_ternary() {
        let mut m = Module {
            name: "m".into(),
            ..Module::default()
        };
        m.inputs.push(port(0, "s", 1, Direction::In));
        m.inputs.push(port(1, "a", 4, Direction::In));
        m.inputs.push(port(2, "b", 4, Direction::In));
        m.outputs.push(port(3, "o", 4, Direction::Out));
        m.nodes.push(Node::PrimaryInput { port: 0, width: 1 }); // 0
        m.nodes.push(Node::PrimaryInput { port: 1, width: 4 }); // 1
        m.nodes.push(Node::PrimaryInput { port: 2, width: 4 }); // 2
        m.nodes.push(Node::Gate {
            op: GateOp::Mux,
            operands: vec![0, 1, 2],
            width: 4,
            deps: DepSet::from_port(0),
        }); // 3
        m.drives.push((3, 3));
        let sv = to_sv(&m);
        assert!(sv.contains("assign mux_0 = (s) ? (a) : (b);"));
    }
}
