//! SystemVerilog pretty-printer. Assumes IR invariants hold; does not
//! validate.

use crate::ir::{GateOp, Module, Node, NodeId};
use std::fmt::Write;

pub fn to_sv(m: &Module) -> String {
    let mut out = String::new();
    writeln!(out, "// Generated by anvil. Module: {}", m.name).unwrap();
    writeln!(out, "module {} (", m.name).unwrap();

    let mut first = true;
    for p in &m.inputs {
        if !first {
            writeln!(out, ",").unwrap();
        }
        first = false;
        write!(out, "    input  logic {} {}", width_decl(p.width), p.name).unwrap();
    }
    for p in &m.outputs {
        if !first {
            writeln!(out, ",").unwrap();
        }
        first = false;
        write!(out, "    output logic {} {}", width_decl(p.width), p.name).unwrap();
    }
    writeln!(out).unwrap();
    writeln!(out, ");").unwrap();
    writeln!(out).unwrap();

    // Emit internal wire declarations for every Gate node.
    for (idx, node) in m.nodes.iter().enumerate() {
        if let Node::Gate { width, .. } = node {
            writeln!(out, "    wire {} w_{};", width_decl(*width), idx).unwrap();
        }
    }
    writeln!(out).unwrap();

    // Emit `assign` for every Gate node.
    for (idx, node) in m.nodes.iter().enumerate() {
        if let Node::Gate { op, operands, .. } = node {
            let rhs = render_gate(*op, operands, m);
            writeln!(out, "    assign w_{} = {};", idx, rhs).unwrap();
        }
    }
    writeln!(out).unwrap();

    // Emit `assign` for each output port.
    for (port_id, node_id) in &m.drives {
        let out_port = m.outputs.iter().find(|p| p.id == *port_id).unwrap();
        let rhs = node_ref(*node_id, m);
        writeln!(out, "    assign {} = {};", out_port.name, rhs).unwrap();
    }

    writeln!(out, "endmodule").unwrap();
    out
}

fn width_decl(w: u32) -> String {
    if w == 1 {
        String::new()
    } else {
        format!("[{}:0]", w - 1)
    }
}

fn node_ref(id: NodeId, m: &Module) -> String {
    match &m.nodes[id as usize] {
        Node::PrimaryInput { port, .. } => m
            .inputs
            .iter()
            .find(|p| p.id == *port)
            .unwrap()
            .name
            .clone(),
        Node::Constant { width, value } => format!("{}'h{:x}", width, value),
        Node::FlopQ { flop, .. } => format!("r_{}", flop),
        Node::Gate { .. } => format!("w_{}", id),
    }
}

fn render_gate(op: GateOp, operands: &[NodeId], m: &Module) -> String {
    use GateOp::*;
    let a = |i: usize| node_ref(operands[i], m);
    match op {
        And => format!("{} & {}", a(0), a(1)),
        Or => format!("{} | {}", a(0), a(1)),
        Xor => format!("{} ^ {}", a(0), a(1)),
        Not => format!("~{}", a(0)),
        Add => format!("{} + {}", a(0), a(1)),
        Sub => format!("{} - {}", a(0), a(1)),
        Mul => format!("{} * {}", a(0), a(1)),
        Eq => format!("{} == {}", a(0), a(1)),
        Neq => format!("{} != {}", a(0), a(1)),
        Lt => format!("{} < {}", a(0), a(1)),
        Gt => format!("{} > {}", a(0), a(1)),
        Le => format!("{} <= {}", a(0), a(1)),
        Ge => format!("{} >= {}", a(0), a(1)),
        Mux => format!("({}) ? ({}) : ({})", a(0), a(1), a(2)),
        Slice { hi, lo } => format!("{}[{}:{}]", a(0), hi, lo),
        Concat => {
            let parts: Vec<_> = operands.iter().map(|id| node_ref(*id, m)).collect();
            format!("{{{}}}", parts.join(", "))
        }
        RedAnd => format!("&({})", a(0)),
        RedOr => format!("|({})", a(0)),
        RedXor => format!("^({})", a(0)),
        Shl => format!("{} << {}", a(0), a(1)),
        Shr => format!("{} >> {}", a(0), a(1)),
    }
}
